### ISSUE TITLE
LambdaBlockToExpression should keep comments

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#1]
LambdaBlockToExpression seems to remove comments

```diff
-        setResultConverter(button -> {
-            // The buttonType will always be "cancel", even if we pressed one of the entry type buttons
-            return type;
-        });
+        setResultConverter(button -> type);
```

**Comment by timtebeek** [comment]
In this case we probably want to prepend the prefix that was on the `return` to the prefix on the `type` that follows it.

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-static-analysis/pull/114 ; thanks @xshen053 !

**Comment by koppor** [comment]
It would have been nice that my example was added as test case by @xshen053. Maybe in a follow-up PR? 😅

Looking forward to a release 🤩🤩.

**Comment by koppor** [comment]
I close assuming that it's fixed!

**Comment by timtebeek** [comment]
There is a similar test merged though right? Or are you concerned that does not cover your exact case?
https://github.com/openrewrite/rewrite-static-analysis/blob/2b013e2f746fc9fb7cae40424079c8b5cd0ff050/src/test/java/org/openrewrite/staticanalysis/LambdaBlockToExpressionTest.java#L55-L77
You're more than welcome to reproduce if there's still an issue! :)

**Comment by xshen053** [comment]
Plan to solve more issues when I am free 😆

**Comment by koppor** [comment]
> There is a similar test merged though right? 

Yeah, I've seen this

> Or are you concerned that does not cover your exact case?

Yes! I am in the group thinking: more tests do not harm. They can be deleted if they cause harm when refactoring.
