### ISSUE TITLE
ExplicitInitialization removes initialization from final fields when using @Value.

### ISSUE THREAD

**Issue by pstreef** [openrewrite/rewrite-static-analysis#101]
sample:
```
import lombok.Value;
@Value
class Test {
    boolean b = false;
}
```
expected: no change
Actual:
```
import lombok.Value;
@Value
class Test {
    boolean b;
}
```
this results in the field b being added the the @RequiredArgsConstructor. Changing it's signature.

**Comment by timtebeek** [comment]
That's a very specific edge case I hadn't thought of; I think we can make the recipe back off in the presence of lombok.Value, just to be safe here. That would not require Lombok support, as we only look at the presence of the annotation, not what the annotation would result in.
