### ISSUE TITLE
JavaDoc: RemoveJavaDocAuthorTag and RemoveEmptyJavaDocParameters should remove empty JavaDoc after cleanup

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#119]
```diff
 /**
- * @author jzieren
  */
```

Expected:

```diff
- /**
-  * @author jzieren
-  */
```

Similar for `RemoveEmptyJavaDocParameters` - and thus refs https://github.com/openrewrite/rewrite-static-analysis/issues/98.

Maybe both `RemoveJavaDocAuthorTag` and `RemoveEmptyJavaDocParameters` should remove empty lines and empty JavaDoc after cleanup.

**Comment by timtebeek** [comment]
I've added https://github.com/openrewrite/rewrite-static-analysis/pull/120 to hopefully resolve this quickly; It only handles the above case; not also #98 which concerns trimming in addition to removing empty tags. On the PR we can discuss potential broader appliability.

**Comment by koppor** [comment]
@timtebeek Tried it today with recent versions - and JavaDoc is still empty - and not removed:

```diff
 /**
  *
- * @author airhacks.com
  */
 public class Configurator {
```

**Comment by koppor** [comment]
Ah, if there is no `*` around, it works:

```diff
 
-/**
- * @author adam-bien.com
- */
 public class ViewLoader {
 
```

**Comment by timtebeek** [comment]
Ah yes the approach taken in https://github.com/openrewrite/rewrite-static-analysis/pull/120 does not account for additional new lines. With a new unit test and likely small code change that can probably be covered; Would you want to add those changes?
