### ISSUE TITLE
FinalizePrivateFields must not change volatile fields

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-static-analysis#121]
## What is the smallest, simplest way to reproduce the problem?

```java
public final class Reproducer {

    private Reproducer() {
    }

    private static volatile String foo = "this becomes final volatile, which is invalid";

}
```

## What did you expect to see?
same code, unmodified

## What did you see instead?

```java
public final class Reproducer {

    private Reproducer() {
    }

    private static final volatile String foo = "this becomes final volatile, which is invalid";

}
```

Notice the added `final`. A field cannot be both final and volatile, only either or.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, I'll try to create a test and fix.

**Comment by timtebeek** [comment]
Thank you very much for the offer to help! I imagine you're comfortable enough by now to work on a potential fix here without further guidance? It'll start with [adding a unit test](https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/test/java/org/openrewrite/staticanalysis/FinalizePrivateFieldsTest.java), and then likely stepping through with the debugger and potentially updating this filter step. https://github.com/openrewrite/rewrite-static-analysis/blob/fd5c7dc62b25d9831d6798b2b2a5f1a65e1e1233/src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java#L124

**Comment by MehmetTerc** [comment]
I dont understand the Issue, can you describe me the task @Bananeweizen

**Comment by timtebeek** [comment]
> I dont understand the Issue, can you describe me the task

It sounds like @Bananeweizen was already planning to pick this up @MehmetTerc ; there are some [other open issues](https://github.com/orgs/openrewrite/projects/4/views/10?filterQuery=label%3A%22good+first+issue%22) if you're looking to pick up something else.

In this particular case we want to limit the execution of `FinalizePrivateFields` such that it does not update any `volatile` fields, possibly [as described here](https://github.com/openrewrite/rewrite-static-analysis/issues/121#issuecomment-1584711158).
