### ISSUE TITLE
Simplify lambda blocks to expressions replaces return that is used to infer which overloaded method to pick

### ISSUE THREAD

**Issue by pstreef** [openrewrite/rewrite-static-analysis#162]
When an overloaded method that takes either a consumer or Function the lambda can not always be rewritten from a block to an expression, because the return statement is implying that the Function argument is used.

<img width="774" alt="image" src="https://github.com/openrewrite/rewrite-static-analysis/assets/7645564/8a97fb78-91ee-42b9-ba6b-4ca1119fa9a6">

I've created a test that reproduces this issue, but it does not detect the compiler issue that I get when I use the output.

Note intellij also suggests this change.

**Comment by kunli2** [comment]
fixed by https://github.com/openrewrite/rewrite-static-analysis/commit/3c3fdedf86e0c60782c591ac78e28346f3e4fcd5
