### ISSUE TITLE
InstanceOfPatternMatch leads to duplicate variable name in if statement with two different instanceof

### ISSUE THREAD

**Issue by ghost** [openrewrite/rewrite-static-analysis#174]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v5.5.2
- Maven/Gradle plugin v3.11.0
- rewrite-_module_ v2.1.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
    <groupId>org.openrewrite.maven</groupId>
    <artifactId>rewrite-maven-plugin</artifactId>
    <version>5.5.2</version>
    <configuration>
        <activeRecipes>
            <recipe>org.openrewrite.java.migrate.UpgradeToJava20</recipe>
        </activeRecipes>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-migrate-java</artifactId>
            <version>2.1.0</version>
        </dependency>
    </dependencies>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
if (test instanceof TestClass && test2 instanceof TestClass) {
    ...
}
```

## What did you expect to see?

```java
if (test instanceof TestClass t && test2 instanceof TestClass t2) {
    ...
}
```

## What did you see instead?

```java
if (test instanceof TestClass t && test2 instanceof TestClass t) {
    ...
}
```

**Comment by timtebeek** [comment]
Replicated in https://github.com/openrewrite/rewrite-static-analysis/pull/175

**Comment by timtebeek** [comment]
Already much improved in 
- https://github.com/openrewrite/rewrite-static-analysis/pull/175

Closing the issue as I expect any remaining cases to be rare in practice.
