### ISSUE TITLE
FinalizeMethodArguments should consider unary increments/decrements

### ISSUE THREAD

**Issue by AlejandroBertolo** [openrewrite/rewrite-static-analysis#176]
Greetings. Thanks for your work in this useful library!.

We've found a issue with the **[FinalizeMethodArguments](https://docs.openrewrite.org/recipes/staticanalysis/finalizemethodarguments)** recipe, by which unary operators are not considered when deciding if a parameter has been reassigned. This leads to compilation errors in processed source code.

## What version of OpenRewrite are you using?
staticAnalysis 1.0.7 
RecipeBom 2.3.0
RewriteMavenPlugin 5.7.1

## How are you running OpenRewrite?

Through Maven plugin, in a multi-module project.

## What is the smallest, simplest way to reproduce the problem?
The following test generates changes that won't compile.
edit: edited the test for less complexity
```java
package Test;

class Test {

  protected int addFinalToThisVar(int unalteredVariable) {
    return unalteredVariable;
  }

  protected int increment(int variableToIncrement) {
    variableToIncrement++;
    return variableToIncrement;
  }

  protected int preIncrement(int variableToPreIncrement) {
    return ++variableToPreIncrement;
  }

  protected int decrement(int variableToDecrement) {
    variableToDecrement--;
    return variableToDecrement;
  }

  protected int preDecrement(int variableToPreDecrement) {
    return --variableToPreDecrement;
  }

  protected int accumulate(int add, int accumulator) {
    accumulator += add;
    return accumulator;
  }
}

```

## What did you expect to see?
```java
package Test;

class Test {

  protected int addFinalToThisVar(final int unalteredVariable) {
    return unalteredVariable;
  }

  protected int increment(int variableToIncrement) {
    variableToIncrement++;
    return variableToIncrement;
  }

  protected int preIncrement(int variableToPreIncrement) {
    return ++variableToPreIncrement;
  }

  protected int decrement(int variableToDecrement) {
    variableToDecrement--;
    return variableToDecrement;
  }

  protected int preDecrement(int variableToPreDecrement) {
    return --variableToPreDecrement;
  }

  protected int accumulate(final int add, int accumulator) {
    accumulator += add;
    return accumulator;
  }
}
```

## What did you see instead?
```java
package Test;

class Test {

  protected int addFinalToThisVar(final int unalteredVariable) {
    return unalteredVariable;
  }

  protected int increment(final int variableToIncrement) {
    variableToIncrement++;
    return variableToIncrement;
  }

  protected int preIncrement(final int variableToPreIncrement) {
    return ++variableToPreIncrement;
  }

  protected int decrement(final int variableToDecrement) {
    variableToDecrement--;
    return variableToDecrement;
  }

  protected int preDecrement(final int variableToPreDecrement) {
    return --variableToPreDecrement;
  }

  protected int accumulate(final int add, final int accumulator) {
    accumulator += add;
    return accumulator;
  }

```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes. The fix seems easy as it is already implemented in FinalizeLocalVariables. Bringing the VisitUnary and VisitAssignmentOperator logic from that recipe seems to fix the issues (altho the "add" variable in the last test method is not finalized, though that would be a minor concern).

**Comment by timtebeek** [comment]
Thanks for the detailed report @AlejandroBertolo ! Seems like an oversight indeed, and would be good to see fixed. Thanks for offering to help out; let me know if you're able to fit that in, otherwise I can try to fit this in.

Roughly speaking the steps should be:
1. Fork & checkout the project
2. Add a unit test using your above example similar to this one https://github.com/openrewrite/rewrite-static-analysis/blob/0ce5108a9a2438718f14286f7004568e495a9051/src/test/java/org/openrewrite/staticanalysis/FinalizeMethodArgumentsTest.java#L34-L56
3. Update the recipe visitor to take increments into consideration https://github.com/openrewrite/rewrite-static-analysis/blob/0ce5108a9a2438718f14286f7004568e495a9051/src/main/java/org/openrewrite/staticanalysis/FinalizeMethodArguments.java#L54-L58
