### ISSUE TITLE
FinalizePrivateFields wrongly finalizes static field.

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-static-analysis#177]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.7.1

## What is the smallest, simplest way to reproduce the problem?

Add this to FinalizePrivateFieldsTest:
```java
    @Test
    @Issue("TODO")
    void ignoreStaticFieldAssignedInConstructor() {
        //language=java
        rewriteRun(
          java(
            """
              public class Reproducer {

                  private static Reproducer instance;

                  public Reproducer() {
                      instance = this;
                  }

              }
              """
          )
        );
    }
```

## What did you expect to see?

No change.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

This recipe has quite many corner cases judging by the unit tests, someone with more knowledge should have a look at it.

**Comment by vlsi** [comment]
pgjdbc has the same code at https://github.com/pgjdbc/pgjdbc/blob/9cf9f36a1d3a1edd9286721f9c0b9cfa9e8422e3/pgjdbc/src/test/java/org/postgresql/test/socketfactory/CustomSocketFactory.java#L26

**Comment by vlsi** [comment]
A workaround is to remove `private` so the field becomes `package private`.

**Comment by timtebeek** [comment]
Likely fixed in
- https://github.com/openrewrite/rewrite-static-analysis/pull/215

Feel free to do an additional review or provide more test cases.

**Comment by timtebeek** [comment]
Thanks both for reporting this issue; should be fixed in the [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions) already, with release to follow. Let us know if that works for you too!
