### ISSUE TITLE
UseCollectionInterfaces breaks EnumSet iteration

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-static-analysis#179]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.7.1

## What is the smallest, simplest way to reproduce the problem?

```java
        EnumSet<?> values = EnumSet.allOf(MyEnum.class);
        for (Enum<?> e : values) {
            // something
        }
```

## What did you expect to see?
no change

## What did you see instead?

```java
        Set<?> values = EnumSet.allOf(MyEnum.class);
        for (Enum<?> e : values) {
            // something
        }
```
That doesn't compile anymore. For other subclasses of Set, using the super class for the declaration doesn't change the template argument. For EnumSet it does, because EnumSet is defined with a template argument `Enum<E>` extending `Set<E>`. Therefore anx code needing then Enum typing will not compile anymore.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

If some maintainer agrees, I would try to exclude EnumSet from the applicable types in this recipe.

**Comment by timtebeek** [comment]
Looks like we didn't take generics into account when we added this test for `EnumSet`
https://github.com/openrewrite/rewrite-static-analysis/blob/0ce5108a9a2438718f14286f7004568e495a9051/src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java#L666-L689

Good idea then to:
- remove the `after` text block from the test,
- add generics to that test,
- add `@Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/179")` to `void enumSet()`,
- and only then remove this line (or comment it out).
https://github.com/openrewrite/rewrite-static-analysis/blob/0ce5108a9a2438718f14286f7004568e495a9051/src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java#L87

Thanks for pointing this out and the offer to help!
