### ISSUE TITLE
Wrong position for `default` modifier after sorting with `org.openrewrite.staticanalysis.ModifierOrder` recipe

### ISSUE THREAD

**Issue by joteri** [openrewrite/rewrite-static-analysis#187]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.7.1
- rewrite-java v8.5.0
- rewrite-static-analysis v1.0.8

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.7.1</version>
  <configuration>
    ... 
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
interface A {
    public static default void foo(String bar) {
        int i = 5;
    }
}
```

## What did you expect to see?

```java
class A {
    public default static void foo(String bar) {
        int i = 5;
    }
}
```

## What did you see instead?

```java
interface A {
    default public static void foo(String bar) {
        int i = 5;
    }
}
```

After using `org.openrewrite.staticanalysis.ModifierOrder` recipe I expect it to sort modifiers by [Java Language Specification](https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-InterfaceMethodModifier) where `default` modifier ocuppies a place between `abstract` and `static` and not first place as can be seen on recipe output.

I think element `default` should be repositioned on `org.openrewrite.java.tree.J.Type` enum and ocupy the position it belongs in JLS.

## What is the full stack trace of any errors you encountered?

```
There is no stacktrace for this problem.
```

**Comment by knutwannheden** [comment]
@joteri Thanks for the detailed report! I moved the issue to `openrewrite-static-analysis` as that is where the corresponding code is ([production code](https://github.com/openrewrite/rewrite-static-analysis/blob/f30987fa5ce693b4d644d99de1970f70cedef228/src/main/java/org/openrewrite/staticanalysis/ModifierOrder.java#L4) and [tests](https://github.com/openrewrite/rewrite-static-analysis/blob/f30987fa5ce693b4d644d99de1970f70cedef228/src/test/java/org/openrewrite/staticanalysis/ModifierOrderTest.java#L30)).

If you would be interested in supplying a PR to fix this issue, we would be happy to give you some guidance.
