### ISSUE TITLE
ReplaceLambdaWithMethodReference incorrectly replaces org.apache.kafka.streams.kstream.Predicate<K, V>

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-static-analysis#19]
When running `org.openrewrite.java.cleanup.ReplaceLambdaWithMethodReference` on a Kafka Streams application I noticed it replaces a lambda in the following method call incorrectly, leading to a compilation error (luckily).
```
KStream<K, V> filter(final Predicate<? super K, ? super V> predicate);
```
![image](https://user-images.githubusercontent.com/1027334/197511686-887f1d39-77bb-42ff-b8bb-891524d322e9.png)

Figured report it here, as I don't immediately have the time to dive in for a proper fix.

**Comment by koppor** [comment]
Similar issue:

```diff
-                                                .map(file -> (PreviewLayout) new CitationStylePreviewLayout(file, Globals.entryTypesManager))
+                                                .map(PreviewLayout.class::cast)
```

**Comment by timtebeek** [comment]
This recipe has undergone a lot of changes recently, and likely no longer has this issue:
https://github.com/openrewrite/rewrite-static-analysis/commits/v1.1.0/src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
