### ISSUE TITLE
Cover `? true : false`

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#203]
Does OpenRewrite cover the simple rewrite of `? true : false`?

```diff
-        this.isNewItem = (item.extensionProperty().get().equals("")) ? true : false;
+        this.isNewItem = (item.extensionProperty().get().equals(""));
```

Refs https://github.com/openrewrite/rewrite-static-analysis/issues/192

**Comment by timtebeek** [comment]
My first thought was this should be in [SimplifyBooleanExpressionTest](https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionTest.java#L31); but I don't see any such examples in the tests there. Sounds like a good feature request then, for either a new recipe or expanding the existing recipe.

**Comment by timtebeek** [comment]
At it's simplest we might even be able to use our refaster approach to recipe development
```java
public static class TernaryTrueFalse {
    @BeforeTemplate
    String before(boolean expr) {
        return expr ? true : false;
    }

    @AfterTemplate
    String after(boolean expr) {
        return expr;
    }
}
public static class TernaryFalseTrue {
    @BeforeTemplate
    String before(boolean expr) {
        return expr ? false : true;
    }

    @AfterTemplate
    String after(boolean expr) {
        return !(expr);
    }
}
```
Then all we'd need is some tests and we're ready for a PR; would you be up for trying that?

**Comment by timtebeek** [comment]
Required a few small fixes discovered through https://github.com/openrewrite/rewrite-static-analysis/pull/231 but should work now. Thanks for the suggestion! Any next such recipes should be quite easy to implement now.
