### ISSUE TITLE
FallThrough adds break inside lambda thus causing error: break outside switch or loop

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-static-analysis#213]
## What version of OpenRewrite are you using?

org.openrewrite.rewrite.gradle.plugin:6.4.3

## How are you running OpenRewrite?

Gradle plugin + org.openrewrite.staticanalysis.FallThrough

## What is the smallest, simplest way to reproduce the problem?

No idea yet, however, this code reproduces the issue: https://github.com/pgjdbc/pgjdbc/blob/9cf9f36a1d3a1edd9286721f9c0b9cfa9e8422e3/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L532-L550

The diff by OpenRewrite is:

```diff
@@ -543,20 +543,15 @@ public class ConnectionFactoryImpl extends ConnectionFactory {
                 PGProperty.JAAS_LOGIN.getBoolean(info),
                 PGProperty.LOG_SERVER_ERROR_DETAIL.getBoolean(info));
             return void.class;
+            break; // <--- this yields error: break outside switch or loop
           });
           return pgStream;
+          break; // this seems excessive
         } catch (PSQLException ex) {
           // allow the connection to proceed
           if (gssEncMode == GSSEncMode.PREFER) {
             // we have to reconnect to continue
             return new PGStream(pgStream, connectTimeout);
+            break; // this seems excessive
           }
+          break; // this seems excessive
         }
+        break; // this seems to be fine

       default:
         throw new PSQLException(GT.tr("An error occurred while setting up the GSS Encoded connection."),
```

## What did you expect to see?

Code should still compile after FallThrough applies the changes

## What did you see instead?

Compilation fails.

## What is the full stack trace of any errors you encountered?

```
pgjdbc/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java:546: error: break outside switch or loop
            break;
            ^
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

maybe

**Comment by timtebeek** [comment]
Thanks for reporting this issue; I've moved it to the module containing the recipe and visitor.
https://github.com/openrewrite/rewrite-static-analysis/blob/6d9048c86852119be4d552907b404e788fc2efc6/src/main/java/org/openrewrite/staticanalysis/FallThroughVisitor.java#L33-L33
Not yet sure what's needed for a fix, but the first step is likely a minimal reproduction test as for instance seen here
https://github.com/openrewrite/rewrite-static-analysis/blob/8c803a9c50b480841a4af031f60bac5ee443eb4e/src/test/java/org/openrewrite/staticanalysis/FallThroughTest.java#L39-L65
Appreciate the tentative offer to help; even a draft PR only containing such a test would help!

**Comment by knutwannheden** [comment]
Should now look like this:
<img width="948" alt="image" src="https://github.com/openrewrite/rewrite-static-analysis/assets/408765/924ad567-c7ba-43b9-a2ba-288499e69388">

Thanks for reporting!

**Comment by vlsi** [comment]
@knutwannheden , the added `break` at line 551 breaks compilation.

The error message is `ConnectionFactoryImpl.java:557: error: missing return statement`

The code is

```java
  private PGStream enableGSSEncrypted(PGStream pgStream, GSSEncMode gssEncMode, String host, Properties info,
                                    int connectTimeout)
..
    switch (beresp) {
...
        }
        break; // <-- openrewrite adds this break

      default:
        throw new PSQLException(GT.tr("An error occurred while setting up the GSS Encoded connection."),
            PSQLState.PROTOCOL_VIOLATION);
    } // end of switch
  } // end of method // <-- error: missing return statement
```
