### ISSUE TITLE
Use `contentEquals` to compare StringBuilder to a String

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-static-analysis#22]
![image](https://blog.jetbrains.com/wp-content/uploads/2023/01/image-9.gif)

Source https://blog.jetbrains.com/idea/2023/01/intellij-idea-2023-1-eap-2/?_gl=1*wgqxap*_ga*NDc2NTIxNzM3LjE2NzMyODIxOTY.*_ga_9J976DJZ68*MTY4MDI3NDg5Mi4xMS4xLjE2ODAyNzU2ODUuMC4wLjA.&_ga=2.15990002.513565325.1680274893-476521737.1673282196#NewJavainspections

**Comment by timtebeek** [comment]
Hope you don't mind I unassigned you @bhuwanupadhyay 
I want to open this issue back up again to anyone to pick up.
Feel free to open up a draft pull request if you'd like to contribute!

**Comment by rpau** [comment]
@AlekSimpson reported that this is completed
