### ISSUE TITLE
`RemoveToStringCallsFromArrayInstances` should not use `Arrays.toString` on String/PrintStream/PrintWriter.format methods

### ISSUE THREAD

**Issue by philippe-granet** [openrewrite/rewrite-static-analysis#230]
The following code:
```java
    Object[] strings = new Object[]{"foo", "bar"};
    System.out.println(String.format("%s %s", strings));
```
display `foo bar`.  
But `RemoveToStringCallsFromArrayInstances` recipe generate this code::
```java
    Object[] strings = new Object[]{"foo", "bar"};
    System.out.println(String.format("%s %s", Arrays.toString(strings)));
```
that fail with this error:
```
Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%s'
at java.base/java.util.Formatter.format(Formatter.java:2780)
at java.base/java.util.Formatter.format(Formatter.java:2717)
	at java.base/java.lang.String.format(String.java:4150)
	at HelloWorld.main(HelloWorld.java:8)
```
I think `RemoveToStringCallsFromArrayInstances` recipe should not use `Arrays.toString` on `String/PrintStream/PrintWriter format` methods.

**Comment by timtebeek** [comment]
Thanks for the clear and detailed report! That's indeed a bug that could be fixed with checking the surrounding method invocation. Is that also something you'd like to work on?

To be sure: we appreciate every report, but it can be hard to get to everything. Don't be discouraged from reporting more issues even if you don't have time to contribute! :)

**Comment by knutwannheden** [comment]
Good catch! I think the issue here is that the method being called is a varargs method (e.g. `String#format(String, Object...)`) and that the recipe probably doesn't correctly handle that case.

**Comment by philippe-granet** [comment]
> Thanks for the clear and detailed report! That's indeed a bug that could be fixed with checking the surrounding method invocation. Is that also something you'd like to work on?

You're welcome 😀
Sorry, I'd would love to help but I don't have time available at the moment to work on this problem

**Comment by timtebeek** [comment]
The recipe has some handling to explicitly include arrays passed into one of various print/format methods:
https://github.com/openrewrite/rewrite-static-analysis/blob/30b963b9c36f3f1a4c580a0fcc1b36405b9a7e29/src/main/java/org/openrewrite/staticanalysis/RemoveToStringCallsFromArrayInstances.java#L76-L84

It seems as though that wasn't optimal though, as it produced additional perhaps unwanted changes. I've opened a PR with an alternative but would like your input on potential additional cases to cover:
- https://github.com/openrewrite/rewrite-static-analysis/pull/246
