### ISSUE TITLE
org.openrewrite.staticanalysis.RemoveUnusedPrivateFields does not recognize @Data Lombok annotation

### ISSUE THREAD

**Issue by gwydionmv** [openrewrite/rewrite-static-analysis#242]
Hello!

Similar to this other open issue [here](https://github.com/openrewrite/rewrite-static-analysis/issues/8), the recipe RemoveUnusedPrivateFields is deleting private fields even though the class is annotated as @Data. 

I am using 
- OpenRewrite Maven plugin v5.19.0
- rewrite-static-analysis v1.2.0

I can help working on fixing this issue if you find it interesting too :D

**Comment by timtebeek** [comment]
Hi @gwydionmv ! Thanks for pointing that out and offering to help.

I imagine the fix would be similar to what we do for explicit initialization:
https://github.com/openrewrite/rewrite-static-analysis/blob/a5dc2f7049f7ef4554180c630af75985d388ac4b/src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java#L59-L62
Which we then test here
https://github.com/openrewrite/rewrite-static-analysis/blob/6a38549b00cad1088fc1588c4ba1f645113bb991/src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java#L66-L81

**Comment by timtebeek** [comment]
We would likely need similar handling in `RemoveUnusedPrivateFields`
https://github.com/openrewrite/rewrite-static-analysis/blob/e57dac0991cf3e57edf99826d975c079d0971baf/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java#L67-L68
And best to have a matching test as well in
https://github.com/openrewrite/rewrite-static-analysis/blob/23ee04cc6c9baff6677a5c7efc233f28cd244b1c/src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFieldsTest.java#L26-L30

**Comment by timtebeek** [comment]
Would be much appreciated if you could provide a fix for that, which I'll gladly review shortly. We can then do the same for #8 too.

**Comment by gwydionmv** [comment]
I just created the PR @timtebeek 😄  https://github.com/openrewrite/rewrite-static-analysis/pull/244

**Comment by timtebeek** [comment]
Many thanks! Fixed in
- https://github.com/openrewrite/rewrite-static-analysis/pull/244
