### ISSUE TITLE
FixStringFormatExpressions wrongly replaces `\\n`

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-static-analysis#260]
## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    void foo(String bar) {
       return """
                  \\n
                  """.formatted(bar);
    }
}
```

## What did you expect to see?
the code remaining as is.

## What did you see instead?

```java
class A {
    void foo(String bar) {
        return """
                   \%n
                   """.formatted(bar);
    }
}
```
That's an invalid escape sequence. Root cause of the bug is the recipe replacing `\n` without ever checking if that's part of `\\n`.

Be aware that even though the test _looks_ like it contains the double backslash in the test code, it doesn't. The text block contains double backslash, but that only generates the Java test input, which contains a single backslash.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes. But too tired to look into that now.

**Comment by timtebeek** [comment]
Thanks for the report @Bananeweizen ! I've pushed a quick attempt up at
- https://github.com/openrewrite/rewrite-static-analysis/pull/261

Could use a review as there's a ton of slashes involved. 😅
