### ISSUE TITLE
UseAsBuilder needs a clearer description

### ISSUE THREAD

**Issue by timo-abele** [openrewrite/rewrite-static-analysis#263]
After looking at the tests, the description makes sense, but initially I was hoping that this recipe could turn (actual lombok) setter calls into a builder call chain, so for:

```java
@Setter
class A {
    private int foo;
    private int ba;
}
```
before:
```java
A a = new A();
a.setFoo(1);
a.setBa(2);
```
after:
```java
A a = A.builder().foo(1).ba(2);
```

I think "series of setter calls" is what tripped me up and let me think that a builder would be added where so far no builder had been. I suggest something like "chain builder calls" and, if possible a code snippet.

**Comment by timtebeek** [comment]
Good feedback, thanks! Looking at the recipe these are the current displayName and description.
https://github.com/openrewrite/rewrite-static-analysis/blob/6fc920533401e0f9a098fde655bc648d4dfb4087/src/main/java/org/openrewrite/staticanalysis/UseAsBuilder.java#L59-L65

Whereas indeed the test is clearer about the before/after 
https://github.com/openrewrite/rewrite-static-analysis/blob/6fc920533401e0f9a098fde655bc648d4dfb4087/src/test/java/org/openrewrite/staticanalysis/UseAsBuilderTest.java#L50-L75

We'd previously shown the `@DocumentExample` in the description, which could be a way to surface more clearly what a recipe does
- https://github.com/openrewrite/rewrite-build-gradle-plugin/issues/20

Until then, it's probably best to change the name and description to cover what would help prevent confusion. Any suggestions?

**Comment by timo-abele** [comment]
I thought there was a recipe that chains AssertJ asserts from separate lines that I could use for inspiration, but I can no longer find it 🫤 -> feature request
I would suggest:
Class Name: ChainCallsToBuilderMethods
Recipe Name: Chain calls to builder methods on separate lines into one chain of builder calls.
Recipe Description: When an API has been designed as a builder, join method invocations into one call chain
Feel free to adjust, I will not have the time to make a PR for this.
