### ISSUE TITLE
`SimplifyConstantIfBranchExecution` unconditionally removes braces

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-static-analysis#286]
## What is the smallest, simplest way to reproduce the problem?

```java
    @Test
    @Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/286")
    void doNotChangeParenthesisOnly() {
        rewriteRun(
          //language=java
          java(
            """
              public class A {
                  public void test() {
                      boolean b = true;
                      if (!(b)) {
                          System.out.println("hello");
                      }
                  }
              }
              """
          )
        );
    }
```

## What did you expect to see?
No change.

## What did you see instead?
Braces removed around `b`. `SimplifyConstantIfBranchExecution` unconditionally calls further visitors to optimize away also braces, unneeded block statements etc. I can understand that this makes sense for the case that it actually can simplify an if-condition before or after calling those other visitors. But if it cannot do any optimization on its own, then returning the result of brace removal is wrong. I have disabled the recipe for removing braces.

```java
    expected: "public class A {
        public void test() {
            boolean b = true;
            if (!(b)) {
                System.out.println("hello");
            }
        }
    }"
     but was: "public class A {
        public void test() {
            boolean b = true;
            if (!b) {
                System.out.println("hello");
            }
        }
    }"
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe. I'm not sure of a good way to differentiate the two cases yet.

**Comment by timtebeek** [comment]
You're right; it seems we unconditionally run the other visitors.
https://github.com/openrewrite/rewrite-static-analysis/blob/456f278dccb61e48db817cbe7c4122ba77f96727/src/main/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecution.java#L91-L92

Perhaps it would make sense here to only run those other visitors if running the changes in `SimplifyConstantIfBranchExecutionVisitor` `visitIf` itself results in changes; that way this recipe can run in isolation and only makes changes where there's an actual if branch to simplify.

**Comment by Bananeweizen** [comment]
It seemed more simple to just remember the unoptimized node and to return it in case the if-condition was not simplified.
