### ISSUE TITLE
UseLambdaForFunctionalInterface should exclude methods with type paramters

### ISSUE THREAD

**Issue by mbruggmann** [openrewrite/rewrite-static-analysis#309]
We are using OpenRewrite v8.28.1 and rewrite-static-analysis v1.10.1.

In our codebase, we have an interface with a single method using a type parameter. Something like this:
```java
public interface I {
  <T> List<T> call();
}
```

Which is then implemented in other places using an anonymous class like so:
```java
final I i = new I() {
  @Override
  public <T> List<T> call() {...}
};
```

The `UseLambdaForFunctionalInterface` recipe replaces such inline definitions of `I` with a lambda (`final I i = () -> ...;`). That will not compile because of the type argument being lost. I would expect the recipe to bail out and not introduce a lambda in this case.

I can reproduce it using this testcase:
```java
  @Test
  void dontUseLambdaForMethodWithTypeParameter() {
    rewriteRun(
        spec -> spec.recipe(new UseLambdaForFunctionalInterface()),
        java(
            // can't transform to lambda because of the type argument of I#call()
            """
            package com.helloworld;

            import java.util.List;

            public interface I {
              <T> List<T> call();
            }

            class Hello {
              public void hello() {
                final I i = new I() {
                  @Override
                  public <T> List<T> call() {
                    return null;
                  }
                };
                final List<String> list = i.call();
              }
            }
            """));
  }
}
```

**Comment by timtebeek** [comment]
Thanks for the runnable example @mbruggmann ; I've had a brief look locally with these minor changes to your test.

```java
@Test
@Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/309")
void dontUseLambdaForMethodWithTypeParameter() {
    //language=java
    rewriteRun(
      spec -> spec.parser(JavaParser.fromJavaVersion().dependsOn(
        """
          package com.helloworld;

          import java.util.List;

          public interface I {
            <T> List<T> call();
          }
          """
      )),
      java(
        // can't transform to lambda because of the type argument of I#call()
        """
          package com.helloworld;

          import java.util.List;

          class Hello {
            public void hello() {
              final I i = new I() {
                @Override
                public <T> List<T> call() {
                  return null;
                }
              };
              final List<String> list = i.call();
            }
          }
          """
      )
    );
}
```

Did you already explore any potential fixes for this recipe?

**Comment by timtebeek** [comment]
I've pushed up the above test to https://github.com/openrewrite/rewrite-static-analysis/commit/045bd00edc307fd585e8892fc1f297e95606b074 if you want to have a look.

Earlier we had handled another case differently by introducing casting; perhaps good to compare:
- https://github.com/openrewrite/rewrite-static-analysis/pull/207

**Comment by mbruggmann** [comment]
Thanks @timtebeek!
I haven't had a chance to look at possible fixes, but wanted to make sure we capture the issue at least.
