### ISSUE TITLE
`UseStringReplace` is overly cautious around the use of `=`

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-static-analysis#330]
## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    void foo(String bar) {
        bar.replace("=","|");
    }
}
```

## What did you see instead?

```java
class A {
    void foo(String bar) {
        bar.replaceAll("=","|");
    }
}
```

https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/main/java/org/openrewrite/staticanalysis/UseStringReplace.java#L77 seems to just scan?

**Comment by timtebeek** [comment]
Hi @blipper ; Could it be that you flipped the before and after examples here? Since we go from `replaceAll` to `replace` when we can safely do so. Here's the test I think you meant that indeed replicates nothing is done currently.

```java
@Test
@Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/330")
void overlyCautious() {
    //language=java
    rewriteRun(
      java(
        """
          class A {
              String foo(String bar) {
                  return bar.replaceAll("=","|");
              }
          }
          """,
        """
          class A {
              String foo(String bar) {
                  return bar.replace("=","|");
              }
          }
          """
      )
    );
}
```

**Comment by timtebeek** [comment]
It looks like we're indeed cautious excluding that `=`, even if that's only in these patterns:
https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html

> Special constructs (named-capturing and non-capturing)
> 
> | Construct | Matchers |
> | -- | -- |
> | (?=X) | X, via zero-width positive lookahead |
> | (?<=X) | X, via zero-width positive lookbehind |

As a quick glance we can change that `METACHARACTERS` to something like the following to get the test to pass.

```diff
- private static final Pattern METACHARACTERS = Pattern.compile("[(\\[{\\\\^\\-=$!|\\]})?*+.]");
+ private static final Pattern METACHARACTERS = Pattern.compile("[(\\[{\\\\^\\-$!|\\]})?*+.]|\\?=|<=");
```
