### ISSUE TITLE
org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods does not respect @SuppressWarnings("all")

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-static-analysis#331]
## What is the smallest, simplest way to reproduce the problem?

```java
@SuppressWarnings("all")
class A {
    private void foo() {
    }
}
```

## What did you expect to see?

```java
@SuppressWarnings("all")
class A {
    private void foo() {
    }
}
```

## What did you see instead?

```java
@SuppressWarnings("all")
class A {
}
```

Needs to check for both `unused` and `all`.

https://github.com/openrewrite/rewrite-static-analysis/blob/38e00480fbb4e5356bce48eefc3b1c79d5361474/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java#L67-L79

**Comment by timtebeek** [comment]
Thanks @blipper ; know that you're always welcome to immediately open a PR; no need to open an issue first. :)

**Comment by blipper** [comment]
Yeah.  I have a backlog of bugs that I suggested to help out to get to but need to spin up github integrated.  Amazon doesn't use git and build system is different so it takes some work to get setup.
