### ISSUE TITLE
RemoveUnusedLocalVariables requires ignoreVariablesNamed in 1.15.0

### ISSUE THREAD

**Issue by protocol7** [openrewrite/rewrite-static-analysis#333]
## What version of OpenRewrite are you using?

org.openrewrite:rewrite-core:8.34.0
org.openrewrite.recipe:rewrite-static-analysis:1.15.0

## What is the smallest, simplest way to reproduce the problem?

Starting in org.openrewrite.recipe:rewrite-static-analysis:1.15.0, `RemoveUnusedLocalVariables` requires the `ignoreVariablesNamed` property to be configured. We use declarative recipes, including:

```
- org.openrewrite.staticanalysis.RemoveUnusedLocalVariables
```

Upgrading to 1.15.0, this broke with:
Missing{property='RemoveUnusedLocalVariables.ignoreVariablesNamed', value='null', message='is required'}

Configuring the `ignoreVariablesNamed` property works around this, e.g.:
```
  - org.openrewrite.staticanalysis.RemoveUnusedLocalVariables:
      ignoreVariablesNamed: []
```

`RemoveUnusedLocalVariables` was last changed in this PR which changes a large number of recipes, so not sure if this only impacts this recipe.
- https://github.com/openrewrite/rewrite-static-analysis/pull/327

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe, but currently time constrained.

**Comment by timtebeek** [comment]
https://jspecify.dev/docs/user-guide/#type-use-annotation-syntax

> For an array type, if you want to say that the elements of the array can be null then the syntax is @Nullable String[]. If you want to say that the array itself can be null then the syntax is String @Nullable []. And if both the elements and the array itself can be null, the syntax is @Nullable String @Nullable [].

Looks like we're using the annotation incorrectly: we want to assert that the array itself can be null. Fun times.
https://github.com/openrewrite/rewrite-static-analysis/blob/e83ddf9a44c5202d8ba656cbdb14f3c219d7c8b8/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java#L44-L45

Would likely need a fix elsewhere as well; not a complicated one, but a bit of work. Any help appreciated!
