### ISSUE TITLE
RemoveMethodCallVisitor doesn't work in fluent APIs

### ISSUE THREAD

**Issue by mbruggmann** [openrewrite/rewrite-static-analysis#339]
## What version of OpenRewrite are you using?
I am using
- OpenRewrite 8.34.4
- rewrite-static-analysis 1.15.0

## What is the smallest, simplest way to reproduce the problem?
The RemoveMethodCallVisitor does not seem to work in fluent APIs.
I can reproduce it using this testcase:
```java
  @Test
  void removeMethodCallFromFluentChain() {
    final MethodMatcher methodMatcher = new MethodMatcher("java.lang.StringBuilder append(..)");
    final TreeVisitor<?, ExecutionContext> visitor =
        new RemoveMethodCallVisitor<>(methodMatcher, (i, e) -> true);
    rewriteRun(
        spec -> spec.recipe(RewriteTest.toRecipe(() -> visitor)),
        // language=java
        java(
            """
            class Main {
                void hello() {
                    final String s = new StringBuilder("hello")
                            .append("world")
                            .delete(1, 2)
                            .toString();
                }
            }
            """,
            """
            class Main {
                void hello() {
                    final String s = new StringBuilder("hello")
                            .delete(1, 2)
                            .toString();
                }
            }
            """));
  }
```

## What did you expect to see?
RemoveMethodCallVisitor should work even in fluent chains.

## What did you see instead?
The visitor does not find any invocations except the last one in the fluent chain.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Potentially yes, but this might be an easy fix for someone familiar with the codebase.

**Comment by timtebeek** [comment]
Hi! Explored this briefly, but there's some unexpected results; Naively one might expect it'd be as simple as
```java
if (methodCall instanceof J.MethodInvocation) {
    return ((J.MethodInvocation) methodCall).getSelect();
}
```
However, there's a couple complications: the return type might change, such as in this case from `J.MethodInvocation` to `J.NewClass`, meaning we can no longer extend `JavaIsoVisitor` but should instead extend `JavaVisitor`, necessitating a change for consumers.

Additionally have the existing test `doesNotRemoveAssertTrueIfReturnValueIsUsed` that retains `int value = assertTrue(true);`; not sure if we can change the contract there or need to keep it the same, but it'd be impacted by the above return too.

Welcome to explore more, but figured give some quick first feedback that it's not a quick trivial change. :)

**Comment by mbruggmann** [comment]
Ah good points @timtebeek, I agree it's more complicated than I thought.

Our internal case is for builder chains such as:
```java
SomeClass.builder()
  .withX(...)
  .withY(...)
  .build();
```
Where I would like to be able to remove setting one of the fields (such as `withX(..)`), or sometimes remove a field with a particular value (such as `withY(argumentType==A)` or `withY(argumentValue==B)`).

Do you think it's worth to add a special case for when the select is also a `MethodInvocation` of the same type, or would we rather not make RemoveMethodCallVisitor more confusing and descope this altogether? I don't mind either way, we can have a custom visitor for builders on our side as well.

**Comment by timtebeek** [comment]
Nice to see this fixed before I got a chance to reply; the reduced scope certainly helped to not have to change the contract by too much. Thanks again!
