### ISSUE TITLE
org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods does not clean up imports

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-static-analysis#358]
## What is the smallest, simplest way to reproduce the problem?

```java
import java.util.HashMap;
class A {
    private static void foo() {
        HashMap<String, String> m = new HashMap<>();
    }
}
```

## What did you expect to see?

```java
class A {
}
```

## What did you see instead?

```java
import java.util.HashMap;
class A {
}
```

This is a problem again for any linting/enforcement that will break the build.

It looks like it should remove but doesn't?  https://github.com/openrewrite/rewrite-static-analysis/blob/6646f06a29dd7dee48674dc3389959036fcfe47d/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java#L127

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

**Comment by timtebeek** [comment]
Hi @blipper ; Do note that the line you refer to was only [added five days ago](https://github.com/openrewrite/rewrite-static-analysis/commit/34b5938ff4f2610a92ddef9063ed223b8768f659), and [released two days ago](https://github.com/openrewrite/rewrite-static-analysis/releases/tag/v1.18.0). I'm not sure you're using that exact latest version, so I'll optimistically close the issue, but we can reopen if you're on the latest and still see this issue.

**Comment by blipper** [comment]
Yeah..  I'm using 8.34.0

**Comment by blipper** [comment]
Actually I'm a dummy.  I reported the same thing last week... Which is why it was fixed haha.
