### ISSUE TITLE
[README] Dead link "Browse a selection of recipes available through this module in the recipe catalog."

### ISSUE THREAD

**Issue by bugwelle** [openrewrite/rewrite-static-analysis#386]
## What version of OpenRewrite are you using?

none

## How are you running OpenRewrite?

n/a

## What is the smallest, simplest way to reproduce the problem?

Click on "Browse [a selection of recipes available through this module in the recipe catalog](https://docs.openrewrite.org/recipes/staticanalysis-1)." in the README file of this repository.

See https://github.com/openrewrite/rewrite-static-analysis/blob/81341a8acebf19160e7add46561f73df08f8c5f8/README.md?plain=1#L14

## What did you expect to see?
Documentation site.

## What did you see instead?

404 - not found

## What is the full stack trace of any errors you encountered?
n/a

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

not at the moment, maybe in the future

**Comment by timtebeek** [comment]
Thanks for the headsup @bugwelle ! ❤️
