### ISSUE TITLE
org.openrewrite.staticanalysis.NestedEnumsAreNotStatic is damaging files (non-Java)

### ISSUE THREAD

**Issue by MartinAhrer** [openrewrite/rewrite-static-analysis#400]
Running `NestedEnumsAreNotStatic` from the latest BOM is damaging files.

```
All sources parsed, running active recipes: org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to src/main/resources/application.properties by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradle/wrapper/gradle-wrapper.jar by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradlew by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradlew.bat by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradle/wrapper/gradle-wrapper.properties by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradle/wrapper/gradle-wrapper.jar by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradle/wrapper/gradle-wrapper.properties by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to .gitattributes by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to .gitignore by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to README.adoc by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradlew by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
Changes have been made to gradlew.bat by:
    org.openrewrite.staticanalysis.NestedEnumsAreNotStatic
```

I am using gradle with

plugin  id 'org.openrewrite.rewrite' version '6.28.1'
and recipe dependencies
    rewrite platform('org.openrewrite.recipe:rewrite-recipe-bom:2.23.1')
    rewrite 'org.openrewrite.recipe:rewrite-static-analysis'

A workaround is to use BOM 2.23.0

I have pushed a sample project along with a README showing the issue at

https://github.com/MartinAhrer/open-rewrite-NestedEnumsAreNotStatic

**Comment by timtebeek** [comment]
Thanks for noticing an reporting in such detail @MartinAhrer ; This looks to have slipped in with
- https://github.com/openrewrite/rewrite-static-analysis/pull/396 /cc @jevanlingen 

Fixed now with https://github.com/openrewrite/rewrite-static-analysis/commit/ea74635d6f54177c5c786ca8d14ce1555d0a6314 and should roll out to the next release; until then indeed the workaround should help, thanks!

**Comment by motlin** [comment]
Something similar is happening with the new version rewrite-static-analysis 1.22.1.

https://github.com/liftwizard/liftwizard/pull/2714

**Comment by timtebeek** [comment]
@motlin would you mind trying the newer 
https://github.com/openrewrite/rewrite-static-analysis/releases/tag/v2.0.0 ?

**Comment by motlin** [comment]
@timtebeek now it fails to run with `java.lang.NoClassDefFoundError: org/openrewrite/csharp/tree/Cs`

**Comment by timtebeek** [comment]
Thanks for the report! Looks like an oversight; I've logged a separate issue to add in some guards there.
