### ISSUE TITLE
`hashCode` and `toString` should not be called on `array` instances. `RSPEC-2116`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-static-analysis#44]
> While hashCode and toString are available on arrays, they are largely useless. hashCode returns the array’s "identity hash code", and toString returns nearly the same value. Neither method’s output actually reflects the array’s contents. Instead, you should pass the array to the relevant static Arrays method.

```java
    String argStr = args.toString(); // Noncompliant
    int argHash = args.hashCode(); // Noncompliant
```

```java
    String argStr = Arrays.toString(args);
    int argHash = Arrays.hashCode(args);

```

More examples with `Strings`

```java
int[] s = new int[]{1,2,3};
System.out.println(s);
Sytem.out.println(String.format("s=%s",s));

// .. any other usage where a String is expected
```

```java

int[] s = new int[]{1,2,3};
System.out.println(Arrays.toString(s));
Sytem.out.println(String.format("s=%s",Arrays.toString(s)));

// .. any other usage where a String is expected

```

https://rules.sonarsource.com/java/RSPEC-2116

**Comment by timtebeek** [comment]
Some implementation notes:
- both methods are available on all objects, so any implementation is performance sensitive: limit & return early where possible
- probably best to implement `hashCode` separate from `toString`, as that's slightly easier
- `toString()` can also be implied for arguments headed into `String.format`; that's probably best handled in a separate recipe or visitor to check the arguments to `String.format()` and similar methods such as `printf`.

**Comment by timtebeek** [comment]
Reopened until we also merge in the separate recipes for toString https://github.com/openrewrite/rewrite-static-analysis/pull/126
