### ISSUE TITLE
Recipe : sorted set stream should be collected to a LinkedHashSet

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-static-analysis#70]
The following code is incorrect as the there are no guarantees about iteration order in a `HashSet`

```java
                Set<Integer> set = new HashSet<>();
                set.add(5);
                set.add(60);
                set.add(3);

                Set<Integer> sorted = set.stream().sorted().collect(Collectors.toSet());

```

After : 

```java


                Set<Integer> set = new HashSet<>();
                set.add(5);
                set.add(60);
                set.add(3);

                Set<Integer> sorted = set.stream().sorted().collect(Collectors.toCollection(LinkedHashSet::new));
```

**Comment by timtebeek** [comment]
Hope you don't mind I unassigned you @RossZhang-cpu 
I want to open this issue back up again to anyone to pick up.
Feel free to open up a draft pull request if you'd like to contribute!

**Comment by RossZhang-cpu** [comment]
> Hope you don't mind I unassigned you @RossZhang-cpu I want to open this issue back up again to anyone to pick up. Feel free to open up a draft pull request if you'd like to contribute!

No problem. I recently learn and read the source code to try to understand the whole workflow of how one recipe works. Once I understand it, I will create a draft pull request.

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-static-analysis/pull/139 ; thanks again @RossZhang-cpu !
