### ISSUE TITLE
ReplaceLambdaWithMethodReference should keep the lambda at assertThrows

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#86]
```diff
-        assertThrows(UnsupportedOperationException.class, () -> new WrongTreeNodeImplementation());
+        assertThrows(UnsupportedOperationException.class, WrongTreeNodeImplementation::new);
```

**Comment by timtebeek** [comment]
Just to be clear: does the other form not work? Or is there a preference not to use the second form?

**Comment by koppor** [comment]
The second form does not work. One needs to pass an `Executable` to `assertThrows`. The second form is not not an executable. It is a class.

More examples for `assertThrows`: https://howtodoinjava.com/junit5/expected-exception-example/

**Comment by knutwannheden** [comment]
@koppor AFAICT what the recipe does is actually correct. Can you please double-check in your code that this actually results in a compilation error?

**Comment by koppor** [comment]
@knutwannheden It is NOT a compilation error. It is a semantic error. See JUnit5's source for `assertThrows`:

https://github.com/junit-team/junit5/blob/9ea22079959d1c122daa2b5fca459d39d6e2af07/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java#L53

The idea is that a statement is passed to JUnit. And JUnit executes that statement.

More elaborate example:

```
assertThrows(NullPointerException.class, () -> worker.cleanup(null, new BibEntry()));
```

When executing like that, `worker.cleanup` is executed INSIDE JUnit.

If this is rewritten to

```
assertThrows(NullPointerException.class, worker.cleanup(null, new BibEntry()));
```

Then, a cleanup is executed inside the testing class. The result of the cleanup is then passed to JUnit. The exception needs then to be handled inside the testing class - and is NOT treated at JUnit.

---

My wish is more a nice-to-have feature to enable usage of the same OpenRewrite rules in both main and test classes. It is also OK for me to use OpenRewrite only in main classes and skip the tests. I can also configure OpenRewrite twice: One config for main and one config for test.

Nevertheless, the documentation should list, that `ReplaceLambdaWithMethodReference` fails at `assertThrows`.

**Comment by knutwannheden** [comment]
@koppor There appears to be a misunderstanding of some sort, which I hope we can clear up. I fully agree with what you are saying. However, since the recipe doesn't inline the lambda body (as in your example), but replaces the lambda with an equivalent method reference, I still don't understand what problem you see with the recipe in the context of `assertThrows()`.

Here a small example which is similar to what you originally reported. When I execute the following two tests, the behavior is exactly the same and IntelliJ IDEA in fact also proposes to change the lambda into a method reference.

```java
    static class Boom {
        Boom() {
            throw new IllegalStateException("Boom!");
        }
    }

    @Test
    void lambda() {
        assertThrows(IllegalStateException.class, () -> new Boom());
    }

    @Test
    void methodReference() {
        assertThrows(IllegalStateException.class, Boom::new);
    }
```

**Comment by koppor** [comment]
Thank you for the detailed explanation. Closing as #usererror.

**Comment by koppor** [comment]
I found a case, where the rewrite does not work on my side. In case the `new` operator is followed by a method call.

```java
         assertThrows(SQLException.class,
-                () -> new DBMSConnection(
+                new DBMSConnection(
                         new DBMSConnectionPropertiesBuilder()
                                 .setType(dbmsType)
                                 .setHost("XXXX")
                                 .setPort(33778)
                                 .setDatabase("XXXX")
                                 .setUser("XXXX")
                                 .setPassword("XXXX")
                                 .setUseSSL(false)
                                 .setServerTimezone("XXXX")
-                                .createDBMSConnectionProperties())
-                        .getConnection());
+                                .createDBMSConnectionProperties())::getConnection);
```

I think, there is no way to use this method reference here?

Following is not valid Java syntax

    .createDBMSConnectionProperties())::new.getConnection());

**Comment by knutwannheden** [comment]
Yes, that indeed looks like a bug. If you think you can create a reproducer for this, that would be much appreciated. Otherwise I will try to take a look.
