### ISSUE TITLE
EqualsAvoidsNull should keep Optionals semantics

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#97]
Our method `getField` returns and Optional. We convert that to a String by `.orElse("")`.

The rule moves the conversion at the end of of the statement. Thus, the type of `String` is changed to `Optional` during rewrite.

```diff
                                                  .filter(bibEntry -> bibEntry.getField(StandardField.JOURNAL)
                                                                              .orElse("")
                                                                              .equals("Computer Supported Cooperative Work (CSCW)"))
                                                  .filter(bibEntry -> "Computer Supported Cooperative Work (CSCW)"
                                                                              .equals(bibEntry.getField(StandardField.JOURNAL)
                                                                              .orElse("")))
```

Source: https://github.com/JabRef/jabref/blob/99ab75a93d27a6e1b506521dfe0c196e27ddc867/src/test/java/org/jabref/logic/importer/fetcher/SpringerFetcherTest.java#L185

**Comment by rpau** [comment]
@koppor Sorry, but I do not understand why the rule is wrong, if in your codebase, the method [`BibEntry#getField`](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/model/entry/BibEntry.java#L448) returns an Optional<String>, then the expression is comparing in both cases`"Computer Supported Cooperative Work (CSCW)"` with an empty string or the non empty value of `bibEntry.getField(StandardField.JOURNAL)`. I do see the same behavior and types involved. 

Could you provide an example where the original and the new expression produce different results?
