### ISSUE TITLE
RemoveEmptyJavaDocParameters should remove "empty" lines

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-static-analysis#98]
```diff
     /**
      * Renders this page and returns an image representation of itself.
      *
-     * @param width
-     * @param height
+     *
      */
```

Result:

```java
    /**
     * Renders this page and returns an image representation of itself.
     *
     *
     */
```

Better would be 

```java
    /**
     * Renders this page and returns an image representation of itself.
     */
```

**Comment by koppor** [comment]
Similar:

```diff
-     * @param citationGroups
-     * @param style
      *
-     */
+     **/
```

https://github.com/JabRef/jabref/blob/68b72e0a93c1083f79c5710bc5e6f9607f58e07f/src/main/java/org/jabref/logic/openoffice/style/OOProcessNumericMarkers.java#L24

**Comment by timtebeek** [comment]
A similar issue was resolved through https://github.com/openrewrite/rewrite-static-analysis/pull/120
Anyone welcome to produce the same for this recipe.

**Comment by alixina9** [comment]
Hello, I'd like to work on this issue if that's possible.

**Comment by timtebeek** [comment]
Hi @alixina9 , thanks for your offer to help! Would you need any assistance in getting started? Feel free to open a draft pull request that replicates the issue. Once that's open I can assign the issue to you.
